<?php

declare(strict_types=1);

namespace App\Service;

use App\Entity\HealthCanadaLicensedProducer;
use App\Entity\LicenseDocument;
use App\Entity\Organization;
use App\Entity\User;
use App\Enum\LicenseStatus;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Psr\Log\LoggerInterface;

/**
 * KybService — license verification (Know Your Business).
 *
 * Automatic verification strategy:
 *   1. Canada (Health Canada CTS) → verification via public registry
 *   2. USA (METRC) → verification via METRC API (key required)
 *   3. Germany (BfArM) → manual review (no public API)
 *   4. Fallback → manual validation by CultivaTrace admin
 *
 * In dev: all verifications return "verified" after 5s
 * (simulating the API call).
 */
class KybService
{
    public function __construct(
        private readonly EntityManagerInterface $em,
        private readonly MailerInterface $mailer,
        private readonly HttpClientInterface $httpClient,
        private readonly LoggerInterface $logger,
        private readonly string $appEnv = 'dev',
        private readonly string $metrcApiKey = '',
        private readonly string $alertFromEmail = '',
        private readonly string $adminReviewEmail = '',
        private readonly string $adminReviewUrl = '',
        private readonly string $appUrl = '',
        private readonly string $supportEmail = '',
        private readonly bool $devSimulationEnabled = false,
    ) {}

    /**
     * Launches automatic license verification.
     * Called after document upload.
     *
     * @return array{verified: bool, method: string, reason: string|null}
     */
    public function verify(LicenseDocument $license): array
    {
        if ($this->devSimulationEnabled && $license->getLicenseType() === 'ctls_dev') {
            return $this->simulateVerification($license);
        }

        return match ($license->getLicenseType()) {
            'health_canada' => $this->verifyHealthCanada($license),
            'metrc_usa'     => $this->verifyMetrc($license),
            'bfarm_de'      => $this->fallbackManual($license, 'BfArM has no public API'),
            'ansm_fr'       => $this->fallbackManual($license, 'ANSM requires manual review.'),
            'ctls_dev'      => $this->fallbackManual($license, 'Dev-only CTLS simulation is disabled in this environment.'),
            default         => $this->fallbackManual($license, 'Unrecognized license type'),
        };
    }

    public function isDevSimulationEnabled(): bool
    {
        return $this->devSimulationEnabled;
    }

    /**
     * Dev simulation — auto-approves after a fake verification.
     */
    private function simulateVerification(LicenseDocument $license): array
    {
        $this->logger->info('[KYB DEV] Verification simulation', [
            'license' => $this->maskLicense($license->getLicenseNumber()),
            'type'    => $license->getLicenseType(),
        ]);

        if ($license->getLicenseType() === 'ctls_dev') {
            if (!preg_match('/^TEST-CTLS-[A-Z0-9-]{4,}$/', strtoupper($license->getLicenseNumber()))) {
                return [
                    'verified' => false,
                    'method'   => 'simulated',
                    'reason'   => 'Fake CTLS license format must start with TEST-CTLS-',
                ];
            }

            return [
                'verified'   => true,
                'method'     => 'simulated_ctls_dev',
                'expiresAt'  => (new \DateTimeImmutable('+2 years'))->format('Y-m-d'),
                'reason'     => null,
            ];
        }

        // In dev: always approve (unless the number contains "INVALID")
        if (str_contains(strtoupper($license->getLicenseNumber()), 'INVALID')) {
            return [
                'verified' => false,
                'method'   => 'simulated',
                'reason'   => 'Invalid license number (dev simulation)',
            ];
        }

        return [
            'verified'   => true,
            'method'     => 'simulated',
            'expiresAt'  => (new \DateTimeImmutable('+2 years'))->format('Y-m-d'),
            'reason'     => null,
        ];
    }

    /**
     * Health Canada verification via the locally synced daily registry.
     *
     * The registry is populated by SyncHealthCanadaRegistryCommand (app:sync-health-canada-registry)
     * which downloads the official Health Canada CSV:
     *   https://health-products.canada.ca/api/dataset/95c29d8f-3688-4a37-aca0-1a50af7b1c86
     *
     * If the registry is empty (first install), falls back to manual review.
     */
    private function verifyHealthCanada(LicenseDocument $license): array
    {
        $licenseNumber = strtoupper(trim($license->getLicenseNumber()));

        // Synthetic keys generated by app:sync-health-canada-registry use format HC-COMPANY-PROVINCE
        // (multi-segment) — skip the strict format check for those.
        $isSyntheticKey = str_starts_with($licenseNumber, 'HC-');
        if (!$isSyntheticKey && !preg_match('/^[A-Z]{1,3}(-[A-Z]{1,3})?-[A-Z0-9]{3,}$/i', $licenseNumber)) {
            $this->logger->warning('[KYB] Invalid Health Canada license format', [
                'license' => $this->maskLicense($licenseNumber),
            ]);

            return [
                'verified' => false,
                'method'   => 'format_rejected',
                'reason'   => 'Invalid license number format. Accepted formats: LIC-XXXXX, LP-XXXXX, MC-XXXXX, MR-XXXXX.',
            ];
        }

        $repo = $this->em->getRepository(HealthCanadaLicensedProducer::class);

        // Direct license number lookup (works when the registry still carries individual numbers)
        $producer = $repo->findOneBy(['licenseNumber' => $licenseNumber]);

        // Health Canada dropped individual license numbers from their public registry.
        // Fall back to a company-name match using the submitting organisation's name.
        if ($producer === null) {
            $producer = $repo->findOneBy(['companyName' => $license->getOrganization()->getName()]);
        }

        if ($producer === null) {
            // Registry may be empty on first install — fallback to manual review
            $this->logger->info('[KYB] Health Canada — license not found in local registry', [
                'license'    => $this->maskLicense($licenseNumber),
                'suggestion' => 'Run app:sync-health-canada-registry to populate the registry.',
            ]);

            return $this->fallbackManual($license, 'License not found in local Health Canada registry. Manual review required.');
        }

        // Health Canada always requires manual review in production.
        // The registry lookup provides context for the reviewer but does not auto-approve.
        $statusLabel = $producer->getStatus();
        $registryNote = sprintf(
            'Health Canada registry: "%s" — status "%s". Manual review required.',
            $producer->getCompanyName(),
            $statusLabel,
        );

        $this->logger->info('[KYB] Health Canada — license found, submitted for manual review', [
            'license' => $this->maskLicense($licenseNumber),
            'company' => $producer->getCompanyName(),
            'status'  => $statusLabel,
        ]);

        return $this->fallbackManual($license, $registryNote);
    }

    /**
     * METRC verification — official US state API.
     */
    /** US states supported by METRC */
    private const METRC_ALLOWED_STATES = ['co', 'ca', 'or', 'wa', 'ma', 'mi', 'il', 'nv', 'me', 'ak', 'mo', 'md', 'mn', 'mt', 'nm', 'nj'];

    private function verifyMetrc(LicenseDocument $license): array
    {
        if (empty($this->metrcApiKey)) {
            return $this->fallbackManual($license, 'METRC API key not configured');
        }

        $licenseNumber = $license->getLicenseNumber();

        // Strict format validation — prevents subdomain injection and path traversal
        if (!preg_match('/^([A-Z]{2})-([A-Z0-9\-]+)$/i', $licenseNumber, $matches)) {
            return $this->fallbackManual($license, 'Invalid METRC format (expected: ST-XXXXXX)');
        }

        $stateCode = strtolower($matches[1]);
        if (!in_array($stateCode, self::METRC_ALLOWED_STATES, true)) {
            return $this->fallbackManual($license, 'METRC state not supported');
        }

        try {
            $endpoint = sprintf(
                'https://api-%s.metrc.com/v1/licenses/%s',
                $stateCode,
                urlencode($licenseNumber)
            );

            $response = $this->httpClient->request('GET', $endpoint, [
                'auth_basic' => [$this->metrcApiKey, ''],
                'timeout'    => 10,
            ]);

            if ($response->getStatusCode() === 200) {
                $data = $response->toArray();
                return [
                    'verified'  => true,
                    'method'    => 'auto_metrc',
                    'expiresAt' => $data['ExpirationDate'] ?? null,
                    'reason'    => null,
                ];
            }

            return $this->fallbackManual($license, 'License not found in METRC');

        } catch (\Throwable $e) {
            $this->logger->error('[KYB] METRC error', [
                'error'   => $e->getMessage(),
                'license' => $this->maskLicense($licenseNumber),
                'trace'   => $e->getTraceAsString(),
            ]);
            // Return generic message — do not expose internal error details to client
            return $this->fallbackManual($license, 'Unable to verify license via METRC. Manual review required.');
        }
    }

    /**
     * Manual fallback — notifies the CultivaTrace admin by email.
     */
    private function fallbackManual(LicenseDocument $license, string $reason): array
    {
        $this->logger->info('[KYB] Manual fallback', [
            'license' => $this->maskLicense($license->getLicenseNumber()),
            'reason'  => $reason,
        ]);

        $this->notifyAdminForManualReview($license, $reason);

        return [
            'verified' => false,
            'method'   => 'manual',
            'reviewed' => false,
            'reason'   => $reason,
        ];
    }

    /**
     * Applies the verification result to the LicenseDocument
     * and updates the Organization status.
     */
    public function applyVerificationResult(
        LicenseDocument $license,
        array $result,
    ): void {
        $org = $license->getOrganization();
        $reviewed = (bool) ($result['reviewed'] ?? false);

        if ($result['verified']) {
            $license->setStatus('active');
            $license->setVerifiedAt(new \DateTimeImmutable());
            $license->setVerificationMethod($result['method']);
            $license->setRejectionReason(null);

            if (isset($result['expiresAt'])) {
                $license->setLicenseExpiresAt(new \DateTimeImmutable($result['expiresAt']));
                $org->setLicenseExpiresAt(new \DateTimeImmutable($result['expiresAt']));
            }

            $org->setLicenseStatus(LicenseStatus::ACTIVE);
            $this->notifyUserActivated($license);

        } else {
            $isPendingManualReview = $result['method'] === 'manual'
                && !$reviewed
                && $license->getStatus() === LicenseStatus::PENDING->value
                && $org->getLicenseStatus() === LicenseStatus::PENDING;

            if ($isPendingManualReview) {
                $license->setStatus('pending');
                $org->setLicenseStatus(LicenseStatus::PENDING);
            } else {
                $license->setStatus('rejected');
                $license->setVerificationMethod($result['method']);
                $license->setRejectionReason($result['reason']);
                $org->setLicenseStatus(LicenseStatus::REJECTED);
                $this->notifyUserRejected($license);
            }
        }

        $this->em->flush();
    }

    private function notifyAdminForManualReview(LicenseDocument $license, string $reason): void
    {
        if ($this->adminReviewEmail === '' || $this->alertFromEmail === '') {
            $this->logger->warning('[KYB] Manual review notification skipped because KYB email configuration is incomplete.', [
                'licenseId' => (string) $license->getId(),
            ]);

            return;
        }

        try {
            $reviewInstruction = $this->adminReviewUrl !== ''
                ? sprintf("Process this request: %s", $this->adminReviewUrl)
                : 'Process this request via the KYB backoffice configured for this environment.';

            $email = (new Email())
                ->from($this->alertFromEmail)
                ->to($this->adminReviewEmail)
                ->subject('[KYB] Manual review required — ' . $license->getLicenseNumber())
                ->text(sprintf(
                    "Manual review is required.\n\n" .
                    "Organization: %s\n" .
                    "License number: %s\n" .
                    "Type: %s\n" .
                    "Reason: %s\n" .
                    "Submitted on: %s\n\n" .
                    "%s",
                    $license->getOrganization()->getName(),
                    $license->getLicenseNumber(),
                    $license->getLicenseType(),
                    $reason,
                    $license->getSubmittedAt()->format('Y-m-d H:i'),
                    $reviewInstruction,
                ));
            $this->mailer->send($email);
        } catch (\Throwable $e) {
            $this->logger->error('[KYB] Admin email send error', ['error' => $e->getMessage()]);
        }
    }

    private function notifyUserActivated(LicenseDocument $license): void
    {
        if ($this->alertFromEmail === '' || $this->appUrl === '') {
            $this->logger->warning('[KYB] Activation email skipped because KYB user notification configuration is incomplete.', [
                'licenseId' => (string) $license->getId(),
            ]);

            return;
        }

        try {
            $firstUser = $license->getOrganization()->getUsers()->first();
            $userEmail = $firstUser instanceof User ? $firstUser->getEmail() : null;
            if (!$userEmail) return;

            $email = (new Email())
                ->from($this->alertFromEmail)
                ->to($userEmail)
                ->subject('✅ Your CultivaTrace license has been validated')
                ->text(sprintf(
                    "Great news!\n\n" .
                    "Your license %s has been verified and validated.\n" .
                    "You now have access to all CultivaTrace features.\n\n" .
                    "Sign in at %s",
                    $license->getLicenseNumber(),
                    rtrim($this->appUrl, '/')
                ));
            $this->mailer->send($email);
        } catch (\Throwable $e) {
            $this->logger->error('[KYB] Activation email error', ['error' => $e->getMessage()]);
        }
    }

    private function notifyUserRejected(LicenseDocument $license): void
    {
        if ($this->alertFromEmail === '' || $this->supportEmail === '') {
            $this->logger->warning('[KYB] Rejection email skipped because KYB user notification configuration is incomplete.', [
                'licenseId' => (string) $license->getId(),
            ]);

            return;
        }

        try {
            $firstUser = $license->getOrganization()->getUsers()->first();
            $userEmail = $firstUser instanceof User ? $firstUser->getEmail() : null;
            if (!$userEmail) return;

            $email = (new Email())
                ->from($this->alertFromEmail)
                ->to($userEmail)
                ->subject('❌ CultivaTrace license verification — Action required')
                ->text(sprintf(
                    "Your license verification request could not be validated.\n\n" .
                    "Submitted license: %s\n" .
                    "Reason: %s\n\n" .
                    "Please check your license number and resubmit.\n" .
                    "If the problem persists, contact %s",
                    $license->getLicenseNumber(),
                    $license->getRejectionReason() ?? 'License not recognized',
                    $this->supportEmail,
                ));
            $this->mailer->send($email);
        } catch (\Throwable $e) {
            $this->logger->error('[KYB] Rejection email error', ['error' => $e->getMessage()]);
        }
    }

    private function maskLicense(string $licenseNumber): string
    {
        $visible = min(4, strlen($licenseNumber));
        return substr($licenseNumber, 0, $visible) . str_repeat('*', max(0, strlen($licenseNumber) - $visible));
    }
}
