<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260407133000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add organization admin settings fields and invitations.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE organization ADD contact_email VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE organization ADD config JSONB NOT NULL DEFAULT '{}'");
        $this->addSql("CREATE TABLE organization_invitation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id UUID NOT NULL, invited_by_id INT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, token_hash VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, accepted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_131B11B1D474FA0B ON organization_invitation (token_hash)");
        $this->addSql("CREATE INDEX IDX_131B11B132C8A3DE ON organization_invitation (organization_id)");
        $this->addSql("CREATE INDEX IDX_131B11B1AB0ABBE2 ON organization_invitation (invited_by_id)");
        $this->addSql("ALTER TABLE organization_invitation ADD CONSTRAINT FK_131B11B132C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE organization_invitation ADD CONSTRAINT FK_131B11B1AB0ABBE2 FOREIGN KEY (invited_by_id) REFERENCES \"user\" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
    }

    public function down(Schema $schema): void
    {
        $this->addSql("ALTER TABLE organization_invitation DROP CONSTRAINT FK_131B11B132C8A3DE");
        $this->addSql("ALTER TABLE organization_invitation DROP CONSTRAINT FK_131B11B1AB0ABBE2");
        $this->addSql("DROP TABLE organization_invitation");
        $this->addSql("ALTER TABLE organization DROP contact_email");
        $this->addSql("ALTER TABLE organization DROP config");
    }
}
